# Site Settings
title: "Yilin He"
tagline: "Here is personal website of Yilin He. Powered by Jekyll, based on the Minimal Mistakes theme."
description: "Less is more."
url: "https://lysandre001.github.io"
baseurl: ""

# Theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Author
author:
  name: "Yilin He"
  avatar: "/assets/images/yilin2.png"
  bio: "κρίτης μὴ κάθησο"
  location: "Macau SAR, China "
  email: "lysandreho@163.com"
  links:
    - label: "CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/cv/Yilin_cv.pdf"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yilin-he-926bab14a/"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "ohno!"
    - label: "JIKE"
      icon: "fab fa-fw fa-jike"
      url: "https://web.okjike.com/u/E5B4D547-FDF6-468A-B360-62158C54E5FE"
# Navigation
navigation:
  - title: "About Me"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "Resources"
    url: "/resources/"
  - title: "Gallery"
    url: "/gallery/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
