# Site Settings
title: "Yilin He"
tagline: "Here is personal website of Yilin He. Powered by Jekyll, based on the Minimal Mistakes theme."
description: "Less is more."
url: "https://lysandreho001.github.io"
baseurl: ""

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Author
author:
  name: "Yilin He"
  avatar: "/assets/images/yilin.jpg"
  bio: "CS PHD student at the University of Macau"
  location: "Macau SAR, China "
  email: "lysandreho@163.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:lysandreho@163.com"
    - label: "CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/cv/Yilin_cv.pdf"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yilin-he-926bab14a/"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "ohno!"
    - label: "JIKE"
      icon: "fab fa-fw fa-jike"
      url: "https://www.zhihu.com/people/chlire"
# Navigation
navigation:
  - title: "About Me"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "Resources"
    url: "/resources/"
  - title: "Gallery"
    url: "/gallery/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true